/**
 * Some data to use for our form options
 */
export default {
    reasons: [
        'Looking for trustworthy marketing partner',
        'Looking for more volume',
        'Looking for better quality in injuries',
        'Looking for cheaper leads',
        'Referred',
    ],
    decisionMaker: ['Decision Maker', 'Manager - Needs Approval', 'Influencer'],
    industryCategory: [
        'Broker',
        'Clinic',
        'DME',
        'Hearing Center',
        'Home Healthcare',
        'Insurance',
        'Lab',
        'Marketing Company',
        'Optical Services',
        'Pharmaceutical Company',
        'Pharmacy - Retail',
        'Pharmacy - Mail Order',
        'Pharmacy Network',
        'Senior Products',
        'Unknown - Ask',
        'Weight Loss',
    ],
    productType: [
        'Diabetes Meter',
        'Diabetes CGM',
        'Pain',
        'Erectile Dysfunction',
        'Orthotics',
        'Oral prescriptions',
        'Health Insurance',
        'Hearing Aides',
        'Foot Bath',
        'Cancer Screening',
        'Catheter',
        'Skin',
        'Home Care',
        'Pain & Diabetic',
        'Pain Cream',
        'Eye Glasses',
        'Skin Psoriasis',
        'Final Expense',
        'Medical Alert',
        'Walk-in Tub',
        'Medical Supplement',
        'Other',
    ],
    deliveryMethod: [
        'Posted (API/CRM)',
        'Transfers (Live Calls)',
        'Upload (Dropbox/SFTP)',
    ],
    leadFormType: [
        'Short (Demographic Info)',
        'Mid (Some extended info)',
        'Long (Full Profile)',
        'Document Retrieval',
    ],
    statesLicensed: [
        'Nationwide USA',
        'Canada',
        'AL',
        'AK',
        'AZ',
        'AR',
        'CA',
        'CO',
        'CT',
        'DE',
        'FL',
        'GA',
        'HI',
        'ID',
        'IL',
        'IN',
        'IA',
        'KS',
        'KY',
        'LA',
        'ME',
        'MD',
        'MA',
        'MI',
        'MN',
        'MS',
        'MO',
        'MT',
        'NE',
        'NV',
        'NH',
        'NJ',
        'NM',
        'NY',
        'NC',
        'ND',
        'OH',
        'OK',
        'OR',
        'PA',
        'RI',
        'SC',
        'SD',
        'TN',
        'TX',
        'UT',
        'VT',
        'VA',
        'WA',
        'WV',
        'WI',
        'WY',
        'Unknown - Ask',
    ],
    insuranceTargeting: [
        'Medicare',
        'Medicaid',
        'Private',
        'Cash',
        'Not Applicable',
        'Unknown - ASK',
    ],
}
